# Generated by Django 5.1.3 on 2024-12-09 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='preferred_category',
            field=models.IntegerField(choices=[(1, 'Baby'), (2, 'Birthday'), (3, 'Books'), (4, 'Clothing'), (5, 'Electronics'), (6, 'Entertainment'), (7, 'Fathers Day'), (8, 'Mothers Day'), (9, 'Retail'), (10, 'Travel'), (11, 'Wedding')], null=True),
        ),
    ]
